### Get all credentials

GET http://localhost:3000/credentials

### Get single credential

GET http://localhost:3000/credentials/Neuefischer
Authorization: {{$dotenv MASTERPASSWORD}}

### Add single entry

POST http://localhost:3000/credentials
Content-Type: application/json

{
  "service": "Neuefischer",
  "username": "jozrk",
  "password": "password"
}

### Delete single credential
DELETE http://localhost:3000/credentials/Neuefischer

### Update credential
PUT http://localhost:3000/credentials/Neuefischer

{
  "service": "Neuefischer",
  "username": "123",
  "password": "456"
}